name: Build-All

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.1

    - name: Restore
      run: |
        msbuild .\src\Helpers -t:restore
        msbuild .\src\Helpers.AndroidX -t:restore
        msbuild .\src\Helpers.Mvvm -t:restore
        msbuild .\src\Helpers.ReactiveUI -t:restore

    - name: Build Helpers
      run: msbuild .\src\Helpers /p:Configuration=Release

    - name: Build Helpers.AndroidX
      run: msbuild .\src\Helpers.AndroidX /p:Configuration=Release

    - name: Build Helpers.Mvvm
      run: msbuild .\src\Helpers.Mvvm /p:Configuration=Release

    - name: Build Helpers.ReactiveUI
      run: msbuild .\src\Helpers.ReactiveUI /p:Configuration=Release
